version: '3'

networks:
  db:
    driver: bridge
  shortener:
    driver: bridge

volumes:
  shortener_db_data:
  kafka_data:

services:
  shortener:
    container_name: shortener_service
    build:
      context: ./shortener
    restart: unless-stopped
    environment:
      SERVER_ADDR: "0.0.0.0:${SHORTENER_SERVER_PORT}"
      POSTGRES_URL: "postgres://${SHORTENER_PG_USER}:${SHORTENER_PG_PASSWORD}@shortener_db:5432/${SHORTENER_PG_DB}"
      KAFKA_ADDR: "${KAFKA_ADDR}"
    networks:
      - db
      - shortener
    depends_on:
      - shortener_db
      - kafka

  shortener_db:
    container_name: shortener_db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${SHORTENER_PG_USER}"
      POSTGRES_PASSWORD: "${SHORTENER_PG_PASSWORD}"
      POSTGRES_DB: "${SHORTENER_PG_DB}"
    volumes:
      - shortener_db_data:/var/lib/postgresql
    networks:
      - db

  gateway:
    container_name: shortener_gateway
    build:
      context: ./gateway
    restart: unless-stopped
    environment:
      SERVER_ADDR: "0.0.0.0:${GATEWAY_PORT}"
      PUBLIC_HOST: "${PUBLIC_HOST}"
      GRPC_SERVER_ADDR: "shortener_service:${SHORTENER_SERVER_PORT}"
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - shortener
    depends_on:
      - shortener

  bot:
    container_name: shortener_tg-bot
    build:
      context: ./bot
    restart: unless-stopped
    environment:
      PUBLIC_HOST: "${PUBLIC_HOST}"
      GRPC_SERVER_ADDR: "shortener_service:${SHORTENER_SERVER_PORT}"
      BOT_TOKEN: "${TG_BOT_TOKEN}"
    networks:
      - shortener
    depends_on:
      - gateway

  kafka:
    container_name: kafka
    image: bitnami/kafka:4.0.0
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:9094
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - shortener

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-shortener-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
    depends_on:
      - kafka
    networks:
      - shortener
