// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/misshanya/url-shortener/gen/go/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// newMockgrpcClient creates a new instance of mockgrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgrpcClient {
	mock := &mockgrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgrpcClient is an autogenerated mock type for the grpcClient type
type mockgrpcClient struct {
	mock.Mock
}

type mockgrpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgrpcClient) EXPECT() *mockgrpcClient_Expecter {
	return &mockgrpcClient_Expecter{mock: &_m.Mock}
}

// ShortenURL provides a mock function for the type mockgrpcClient
func (_mock *mockgrpcClient) ShortenURL(ctx context.Context, in *v1.ShortenURLRequest, opts ...grpc.CallOption) (*v1.ShortenURLResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 *v1.ShortenURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ShortenURLRequest, ...grpc.CallOption) (*v1.ShortenURLResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ShortenURLRequest, ...grpc.CallOption) *v1.ShortenURLResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ShortenURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ShortenURLRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgrpcClient_ShortenURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenURL'
type mockgrpcClient_ShortenURL_Call struct {
	*mock.Call
}

// ShortenURL is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ShortenURLRequest
//   - opts ...grpc.CallOption
func (_e *mockgrpcClient_Expecter) ShortenURL(ctx interface{}, in interface{}, opts ...interface{}) *mockgrpcClient_ShortenURL_Call {
	return &mockgrpcClient_ShortenURL_Call{Call: _e.mock.On("ShortenURL",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockgrpcClient_ShortenURL_Call) Run(run func(ctx context.Context, in *v1.ShortenURLRequest, opts ...grpc.CallOption)) *mockgrpcClient_ShortenURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ShortenURLRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ShortenURLRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockgrpcClient_ShortenURL_Call) Return(shortenURLResponse *v1.ShortenURLResponse, err error) *mockgrpcClient_ShortenURL_Call {
	_c.Call.Return(shortenURLResponse, err)
	return _c
}

func (_c *mockgrpcClient_ShortenURL_Call) RunAndReturn(run func(ctx context.Context, in *v1.ShortenURLRequest, opts ...grpc.CallOption) (*v1.ShortenURLResponse, error)) *mockgrpcClient_ShortenURL_Call {
	_c.Call.Return(run)
	return _c
}
