// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package storage

import (
	"context"
)

const getShortByURL = `-- name: GetShortByURL :one
SELECT short FROM urls WHERE url = $1
`

func (q *Queries) GetShortByURL(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRow(ctx, getShortByURL, url)
	var short string
	err := row.Scan(&short)
	return short, err
}

const getURLByShort = `-- name: GetURLByShort :one
SELECT url FROM urls WHERE short = $1
`

func (q *Queries) GetURLByShort(ctx context.Context, short string) (string, error) {
	row := q.db.QueryRow(ctx, getURLByShort, short)
	var url string
	err := row.Scan(&url)
	return url, err
}

const storeShort = `-- name: StoreShort :exec
INSERT INTO urls (url, short) VALUES ($1, $2)
`

type StoreShortParams struct {
	Url   string
	Short string
}

func (q *Queries) StoreShort(ctx context.Context, arg StoreShortParams) error {
	_, err := q.db.Exec(ctx, storeShort, arg.Url, arg.Short)
	return err
}
