// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package storage

import (
	"context"
)

const getID = `-- name: GetID :one
SELECT id FROM urls WHERE url = $1
`

func (q *Queries) GetID(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRow(ctx, getID, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getURLByID = `-- name: GetURLByID :one
SELECT url FROM urls WHERE id = $1
`

func (q *Queries) GetURLByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getURLByID, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const storeShort = `-- name: StoreShort :one
INSERT INTO urls (url) VALUES ($1)
RETURNING id
`

func (q *Queries) StoreShort(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRow(ctx, storeShort, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}
