name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [ 'shortener', 'gateway', 'bot', 'statistics' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.24'
          cache-dependency-path: ./${{ matrix.module }}/go.sum

      - name: Build
        run: go build -o ${{ matrix.module }} ./cmd
        working-directory: ./${{ matrix.module }}
